language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - "go version | grep '1.3' && go test -v --race"
  - "go version | grep '1.3' || $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN -v --race"

env:
  global:
    secure: "OGotvr9L9/mFiYVxLaVg/Uv7jQtohr5v2qQP37H+t11ZY4sWmWYoqWuCmnzjK/eSXTYIoRk8KHmCLTA0A5Ie89UGlFZmxUkbX8CJeTH//doITBdLV8ETdnDZMsFpyyUu6DxxbA0+aollMJ4aouj3xczz/Jf4bnZQndyurabr/ww="
